### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by hroest** [Vitek-Lab/MSstats#1]
Hi Meena

you seem to have removed the licence here a0920d8c3b706bffad063b1c0d832d136010d616 

was this on purpose or under which licence is MSstats distributed?

**Comment by timosachsenberg** [comment]
Hi @MeenaChoi 
Any news on that issue?

**Comment by jspaezp** [comment]
Despite the fact that its not as an explicit file it is in the description of the package ..
https://github.com/MeenaChoi/MSstats/blob/63feb6e41c2485203ea0deff5eeb6a2505a28d87/DESCRIPTION#L14
