### ISSUE TITLE
BioReplicate in default Spectronaut output

### ISSUE THREAD

**Issue by roberthardt** [Vitek-Lab/MSstats#102]
Dear MSstats-developers,

I stumbled upon a small thing, which potentially causes a slightly wrong analysis of Spectronaut results by MSstats. If one uses the default Spectronaut report export scheme, the Replicate column is included. The problem now is that Spectronaut actually reports in this table the replicate numbers within conditions. So if one has 6 samples in total, with 3 ctrl and 3 treated, then the report will state in the BioReplicate column 1-3 for ctrl and again 1-3 for treated, thus implicating sample pairing. While this situation might be true in some instances (sampling at different timepoints ...), most of the time the correct BioReplicate numbers would be 1 - 6 since all samples are independent from each other.
So I guess one has to change the Replicate column entries before running the SpectronautToMSstats-converter or alternatively add an BioReplicate column with the correct numbering?

Best
Robert

**Comment by mstaniak** [comment]
Hi,
my apologies - I missed this issue - your solution is correct. How common is this problem - should we warn users in documentation for the Spectronaut converter?

**Comment by roberthardt** [comment]
Sorry for not answering earlier. Well I guess it is quite common , if people fill out the experimental design during the Spectronaut search setup procedure. I usually do this because if one does, the QC plots within Spectronaut itself get much clearer/concise labels. But if one does, Spectronaut starts labeling all replicates within the same label/sample group with numbers, which always start at 1 in each group.
Best
Robert

**Comment by mstaniak** [comment]
moving this to #112
