### ISSUE TITLE
Questions about how MSstats deal with zero intensity

### ISSUE THREAD

**Issue by ttmduc** [Vitek-Lab/MSstats#34]
I have been trying to figure out how MSstats is dealing with the zero intensity values. Especially in affinity purification mass spectrometry data where the control has 0 intensity (because the peptide is really not there) and the actual pull down has some intensity. How does it calculate a log2 fold change between the actual pull down and the control? Wouldn't that be undefined?
Thank you very much.

**Comment by mstaniak** [comment]
0 intensity can be treated as a censored missing value and imputed,
however when log2-fc is calculated, 0 intensities are not a problem anymore (the calculation is based on summarized data)
