### ISSUE TITLE
dataProcess stopped for unknown reason

### ISSUE THREAD

**Issue by ttmduc** [Vitek-Lab/MSstats#35]
Hi,
I have been trying to run Msstats on my maxquant output data (see attached). Everytime I was stopped at dataProcess step with the following message:
 Summary of Missingness :

  # transitions are completely missing in at least one of the conditions : 5644

    -> DYAFVHFTSR_2_NA_NA, GCEVFVGK_2_NA_NA, LMMDFDGK_2_NA_NA, NLM(ox)IETTEDTIKK_2_NA_NA, NLMIETTEDTIKK_2_NA_NA ...

  # run with 75% missing observations: NA

Error in if (sum(run.missing < 0.25) != 0) { : 
  missing value where TRUE/FALSE needed

**Comment by mstaniak** [comment]
please let us know if the problem persists after an update, closing the issue for now
