### ISSUE TITLE
Error in dataProcess()

### ISSUE THREAD

**Issue by Douerww** [Vitek-Lab/MSstats#57]
My data comes from [here](https://ftp.pride.ebi.ac.uk/pride/data/proteomes/proteogenomics/differential-expression/RPMID25238572.2-organism-part/proteomics_lfq/out_msstats.csv).
When I run the dataProcess() function, it will report an error:
`Aggregation function missing: defaulting to length`
`Error in factor(work$RUN, levels = unique(work$RUN), labels = seq(1, length(unique(work$RUN)))) : invalid 'labels'; length 2 should be 1 or 1`

If this helps, my code is as follows：
![image](https://user-images.githubusercontent.com/46063443/122924626-8f717800-d398-11eb-8d31-e6e01fa0e860.png)

I have viewed the MSstats code on Github, but I didn't find relevant information, how should I solve it?

**Comment by mstaniak** [comment]
Hi,


looks like you are using old version of MSstats (we retired the cutoffCensored parameter). Please check if the problem persists with v4.0.1

**Comment by mstaniak** [comment]
Sorry about the late response, not sure why I missed the issue

**Comment by Douerww** [comment]
Thanks for reply. After I updated the version of MSstats(v4.1.1), the error message turned into it：
![image](https://user-images.githubusercontent.com/46063443/124375711-3083fb00-dcd6-11eb-8740-1207b1b20751.png)
and my code is:
![image](https://user-images.githubusercontent.com/46063443/124376191-56120400-dcd8-11eb-849d-6e8c4fd43ed6.png)

The rest of my data (also from this site) worked, but I couldn't find the difference between error data and normal data.

**Comment by mstaniak** [comment]
Thanks, looks like the problem carried over from v3 to v4. I'll check what's going on there

**Comment by mstaniak** [comment]
Is this experiment label-free? If so, there should be a single value per feature per run, I can see two values in many cases. They should be aggregated

**Comment by Douerww** [comment]
This experiment is label-free, and is the feature refer to PeptideSequence, PrecursorCharge, FragmentIon, ProductCharge?

**Comment by Douerww** [comment]
This experiment is label-free, and is the feature refer to PeptideSequence, PrecursorCharge, FragmentIon, ProductCharge?
If so, I didn't find two same features in same run.

**Comment by mstaniak** [comment]
My bad, I misread the columns. I'll check again

**Comment by mstaniak** [comment]
Hi,
I found the problem, I just need a bit of time to figure out if it's a problem with the annotation of the dataset (perhaps adding "TechReplicate" column to annotation can solve it) or an implementation problem. I'll let you know as soon as I can

**Comment by mstaniak** [comment]
@Douerww are some of the runs here considered technical replicates?

**Comment by Douerww** [comment]
yes, it is, in this [file](https://ftp.pride.ebi.ac.uk/pride/data/proteomes/proteogenomics/differential-expression/RPMID25238572.2-organism-part/expdesign/PMID25238572-tumor-phenotype.sdrf.tsv)

**Comment by mstaniak** [comment]
I'll double check the solution with the team, but hopefully it will be just a minor change in your annotation

**Comment by Douerww** [comment]
thanks!

**Comment by mstaniak** [comment]
![obraz](https://user-images.githubusercontent.com/20418265/124499525-76b48980-ddbe-11eb-9b3e-ff1a3c23a2d9.png)

We made this example to show you what should be the correct annotation for this dataset. Does it help? Current annotation appears to be wrong. Please let me know if you can fix the annotation based on this screenshot and if dataProcess works with the updated dataset

**Comment by Douerww** [comment]
OK, I will check the annotation based on this screenshot, and test dataProcess again, thanks!

**Comment by Douerww** [comment]
Hi, we think the SDRF annotation file has no problem after a discussion. Can you check the [expdesign](https://ftp.pride.ebi.ac.uk/pride/data/proteomes/proteogenomics/differential-expression/RPMID25238572.2-organism-part/expdesign/experimental_design.tsv) file to find the problem?

**Comment by mstaniak** [comment]
It's the annotation in out_msstats.csv that's the problem. The annotation above is OK, but it doesn't translate to the one in out_msstats.csv

**Comment by mstaniak** [comment]
Please compare unique(out_msstats[, c("BioReplicate", "Condition")] ) to the file you sent me and the screenshot

**Comment by Douerww** [comment]
Our pipeline is: sdrf -> expdesign -> out_msstats, the SDRF annotation file has no problem, and the expdesign file generate out_msstats.
Could you check the expdesign file? It can help us determine the problem is in expdesign or out_mssats.

**Comment by mstaniak** [comment]
I thought I've seen a new message, but I can't see it now. Please correct me if I'm wrong, but it looks like your annotation has 9 conditions instead of 3, because id of bioreplicate was appended to condition label.

**Comment by Douerww** [comment]
Thanks for reply, I deleted that comment so it can't be seen. We will check the expdesign file, and it can help us determine the problem is in expdesign or out_mssats (our pipeline is: sdrf -> expdesign -> out_msstats.csv).
If there is any new development or need your help, I will leave a comment.

**Comment by Douerww** [comment]
Hi, perhaps could you modify the out_msstats.csv? I still didn't find where the problem is.

**Comment by mstaniak** [comment]
how many conditions are there in this experiment?

**Comment by Douerww** [comment]
3: breast tumor (1-3  cm) distant tissue, breast tumor (1-3  cm) distant tissue and breast tumor tissue

**Comment by mstaniak** [comment]
Exactly, and I counted 9 conditions, because bioreplicate ID was appended to Condition ID. Is this correct?

**Comment by Douerww** [comment]
unique(out_msstats["Condition"]) shows 3 conditions, do you mean that MSstats is calculated together with Bioreplicate and Condition?

**Comment by mstaniak** [comment]
![obraz](https://user-images.githubusercontent.com/20418265/125087901-31010500-e0cd-11eb-80eb-fb6acd5e6eef.png)
then we are looking at different datasets

**Comment by mstaniak** [comment]
```
> unique(out_msstats$Condition)
[1] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor tissue|Breast cancer|not applicable|P1|not available|1"                  
[2] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor tissue|Breast cancer|not applicable|P2|not available|2"                  
[3] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor <1 cm near tissue|Breast cancer|not applicable|P3|not available|3"       
[4] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor tissue|Breast cancer|not applicable|P3|not available|3"                  
[5] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor <1 cm near tissue|Breast cancer|not applicable|P1|not available|1"       
[6] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor (1-3  cm) distant tissue|Breast cancer|not applicable|P1|not available|1"
[7] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor (1-3  cm) distant tissue|Breast cancer|not applicable|P3|not available|3"
[8] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor <1 cm near tissue|Breast cancer|not applicable|P2|not available|2"       
[9] "Homo sapiens|breast|not available|breast epithelium|not available|female|breast tumor (1-3  cm) distant tissue|Breast cancer|not applicable|P2|not available|2"
```

**Comment by Douerww** [comment]
![image](https://user-images.githubusercontent.com/46063443/125091576-1ba6cd80-e103-11eb-9ff5-b02655f557d5.png)

**Comment by mstaniak** [comment]
Why/how is your input different from the linked file?

**Comment by Douerww** [comment]
Oh, this is my overesight. I originally guess because the Condition column name is too long, and we need is the intermediate real Condition，so I handled the condition column. But the out_msstats before and after running DataProcess are also wrong.

**Comment by Douerww** [comment]
![image](https://user-images.githubusercontent.com/46063443/125094741-14cd8a00-e106-11eb-9c67-0b0ad2afb398.png)
![image](https://user-images.githubusercontent.com/46063443/125094978-4ba3a000-e106-11eb-8e39-a3b986330eb3.png)

I only extract the real useful information in the original Condition column to generate a new out_msstats file, but run them all report the same error.

**Comment by Douerww** [comment]
Hi, I changed `summaryMethod = 'TMP'` to `summaryMethod = 'linear'`, then it can run normally. But there is a warning message: 
`In summary.lm(fit) : essentially perfect fit: summary may be unreliable`

**Comment by mstaniak** [comment]
Hi, linear is not the recommended summarization method. Please try adding a TechReplicate column to indicate technical replicate

**Comment by mstaniak** [comment]
If the warning about perfect fit is coming from dataProcess, it's completely harmless

**Comment by mstaniak** [comment]
Hi,

it was a legitimate error, but the message or lack of message was wrong. One thing that can be done to solve this is to add TechReplicate column and import the data using update version of MSstatsConvert:
devtools::install_github("Vitek-Lab/MSstatsConvert", ref = "hotfix-techreplicate")
but it needs further discussion. I'm moving the discussion to #65 and related pull request. It will be solved (either via TechReplicate column or better error message) in the next release.
