### ISSUE TITLE
gloabla standard peptides processing error

### ISSUE THREAD

**Issue by MASHUOA** [Vitek-Lab/MSstats#59]
In   .normalizeGlobalStandards 
please change:
`standard = input[PEPTIDE == peptide_name, ]`
into:
`standard = input[PEPTIDE %in% peptide_name, ]`
Or: 
```
for (eachID in  peptide_name){
standard = input[PEPTIDE == peptide_name, ]
}
```
The dataprocess() only takes the peptide sequence as standard and parses them into a list of peptide_charge which may contains multiple entries like peptide_2 and peptide_3.

**Comment by mstaniak** [comment]
Hi,
thanks for letting us know, I'll check the logic again and correct early this week

**Comment by mstaniak** [comment]
Hi,
I'm considering some other minor updates, so this will need to wait a moment before going to Bioconductor, but you can install version that includes your proposed changes by running
```
devtools::install_github("Vitek-Lab/MSstats", ref = "hotfix-global-standards")
```
Please let me know if it fixed the problem for you
