### ISSUE TITLE
Bug in merging fractions

### ISSUE THREAD

**Issue by mstaniak** [Vitek-Lab/MSstats#65]
https://github.com/Vitek-Lab/MSstats/blob/master/R/utils_normalize.R#L280
this line: we test for an error, but dcast never throws it - if there are duplicated values, there's just a warning. What should we test? if any value is larger than 1?
@MeenaChoi

**Comment by daichengxin** [comment]
Hi mstaniak @mstaniak , I encountered the same problem when running dataProcess(). This my data: https://github.com/daichengxin/shared/blob/main/out_msstats_tech.csv. Technical replicate column is added. How to solve this problem？ Thanks

**Comment by daichengxin** [comment]
![image](https://user-images.githubusercontent.com/37200167/144701045-ac8a4e22-3b1c-4094-8400-92897e029b18.png)
Does technical replicate seem to be problematic?

**Comment by mstaniak** [comment]
Hi,

thanks for providing the data, I will let you know what the issue is this week

**Comment by mstaniak** [comment]
@daichengxin quick question: do you have a separate ID for each run? Most importantly, for each of the technical replicates. Sorry I couldn't take care of this earlier

**Comment by mstaniak** [comment]
@daichengxin candidate solution:

```
devtools::install_github("Vitek-Lab/MSstatsConvert", ref = "hotfix-techreplicate")
devtools::install_github("Vitek-Lab/MSstats", ref = "hotfix-fractions-check")
```

Please re-run your analysis after installing these updates and let me know if it's OK now

**Comment by daichengxin** [comment]
> @daichengxin quick question: do you have a separate ID for each run? Most importantly, for each of the technical replicates. Sorry I couldn't take care of this earlier

Yes, have a separate ID for each run and technical replicates.  This is the result of my re-run. I'm not sure if this works properly. 
![image](https://user-images.githubusercontent.com/37200167/146125029-e5ebfad0-e3e9-46cb-8011-f8a5daefedf2.png)

**Comment by mstaniak** [comment]
It's almost OK. The "Aggregate function missing" warning should not happen after installing MSstats from hotfix-fractions-check branch, I will double-check this. I will also check the way technical replicates are counted for logging purposes

**Comment by kkw5710** [comment]
Hi. I have the exact same issue as @daichengxin. I re-ran my analysis after installing the updates posted by @mstaniak and am still getting the same error.
