### ISSUE TITLE
question about dataProcess

### ISSUE THREAD

**Issue by hemingwang** [Vitek-Lab/MSstats#67]
Hi
I meet the question, the levels(QuantData$ProcessedData$GROUP_ORIGINAL) is NULL, and I did not have ProcessedData in QuantData.
When I finish the dataProcess, I only have FeatureLevelData, ProteinLevelData and SummaryMethod, but I did not have ProcessedData.

My code is

head(SRMRawData)
QuantData<-dataProcess(SRMRawData)

QuantData$FeatureLevelData
QuantData$ProteinLevelData
QuantData$SummaryMethod

**Comment by mstaniak** [comment]
ProcessedData was a name until v3,
current version is 4 and ProcessedData is now called FeatureLevelData. That column was renamed GROUP_ORIGINAL -> GROUP

**Comment by hemingwang** [comment]
Thank you very much for your patience to help me!

Heming！

**Comment by mstaniak** [comment]
did it fix the problem? Can we close the issue?
