### ISSUE TITLE
dataProcess function : error. but log says that summarization is done

### ISSUE THREAD

**Issue by MeenaChoi** [Vitek-Lab/MSstats#70]
dataProcess was stopped and no output. But, log file says it is done:

![Screen Shot 2021-08-18 at 5 55 04 PM](https://user-images.githubusercontent.com/4159931/129990896-53e69878-4c5a-4d54-bb55-8f1dc37f0db5.png)

**Comment by mstaniak** [comment]
This is because of the "try" clause around summarization function

**Comment by mstaniak** [comment]
Looks like the same problem as in #65, is this correct?

**Comment by mstaniak** [comment]
Closing this issue, let's move discussion to #65 and related pull request
