### ISSUE TITLE
Wrong x-axis name on groupComparisonPlots

### ISSUE THREAD

**Issue by jinyi12** [Vitek-Lab/MSstats#71]
Hi,

I performed a VolcanoPlot on my data containing a log2FC column.
However the resulting plots have "log10 fold change" as my x-axis.

Can anyone advise on this?

Best,
Jin

![image](https://user-images.githubusercontent.com/48187902/131057713-fb1bcdab-2d53-4d14-bcb3-00788c3338e7.png)

**Comment by mstaniak** [comment]
Hi, does setting logBase.pvalue=2 fix the issue?

**Comment by mstaniak** [comment]
Note: both axes use the same parameter for log base -> bug

**Comment by mstaniak** [comment]
Fixed by #124
