### ISSUE TITLE
Error in MSstatsContrastMatrix.matrix(contrast.matrix, groups) :    Assertion on 'colnames of contrast matrix' failed: Must be equal to set {'Condition1','Condition2','Condition3','Condition4'}, but is {}.

### ISSUE THREAD

**Issue by mariiakokina** [Vitek-Lab/MSstats#72]
I am following [this tutorial](https://www.youtube.com/watch?v=4W9fwYhK7Bw&list=PL2u38g_AG4MH4bc9AZjckRvJhltleGziX&index=6). However the command `unique(quant.maxquant$ProcessedData$GROUP_ORIGINAL)` returns NULL and indeed the quant.maxquant data organized differently (see screenshot). Thus, proceeding with `test.maxquant <- groupComparison(contrast.matrix=comparison, data=quant.maxquant)` returns error Error in MSstatsContrastMatrix.matrix(contrast.matrix, groups) :    Assertion on 'colnames of contrast matrix' failed: Must be equal to set {'Condition1','Condition2','Condition3','Condition4'}, but is {}.
<img width="809" alt="Screenshot 2021-08-27 at 10 43 25" src="https://user-images.githubusercontent.com/63904628/131100126-ca85e8c0-caba-4334-b8c3-f3a2f4e516e7.png">

**Comment by mstaniak** [comment]
Hi, in the current version, there is no GROUP_ORIGINAL column. Please use value of GROUP column instead

**Comment by mariiakokina** [comment]
I added `colnames(comparison)<-c("Condition1", "Condition2", "Condition3", "Condition4")` and it worked! Thanks :)
