### ISSUE TITLE
dataProcess with peptides mapping to multiple proteins errors

### ISSUE THREAD

**Issue by Niveda-S** [Vitek-Lab/MSstats#73]
Hi,

I am running dataprocess and am interested in keeping peptides that map to more than one protein but when I do so, I get the following error:
Subject : T3, Condition : Hypoxic has multiple rows (duplicate rows) for some features 
Error in dataProcess(raw) : 
  Please remove duplicate rows in the list above.

Since this is intentional, are there certain parameters or settings to overcome this issue?

**Comment by mstaniak** [comment]
Unfortunately, no - currently, MSstats only uses unique peptides. Support for shared peptides is a long-term enhancement that we are working on.
There is one workaround, but you will need to take care of normalization. Split the dataset by protein and apply summarization to each protein separately, then combine the results. In this case, it's best to set MBimpute to FALSE IMHO.

**Comment by mstaniak** [comment]
I'll close this issue, but feel free to let me know if I can give some other advice on this topic
