### ISSUE TITLE
Msstats summarize features with 1 measurement

### ISSUE THREAD

**Issue by Niveda-S** [Vitek-Lab/MSstats#74]
Hi,

I am running the dataprocess function and I see that features having one measurement are dropped. Is there a way to retain these features and only drop those that have no measurements at all?

**Comment by mstaniak** [comment]
Features with one measurement can be used by MSstats. They are only removed by converter functions (such as PDtoMSstatsFormat). Please look for an option called removeFewMeasurements. If the problem persists, please provide a reproducible example.

**Comment by Niveda-S** [comment]
Thanks for the response!
1) First, I run SkylinetoMSstatsFormat and have set removeFewMeasurements = FALSE. This does not drop any features with one or more measurements
2) Next, I run dataProcess and have set featureSubset = all and summaryMethod = TMP. In this case, features with one measurement are dropped. This is recorded in the log as below:
 ```
== Start the summarization per subplot...
Can't summarize for   ( 12  of  1702 ) because features have only one measurement across MS runs.
Can't summarize for   ( 18  of  1702 ) because features have only one measurement across MS runs.
Can't summarize for   ( 26  of  1702 ) because features have only one measurement across MS runs.
Can't summarize for   ( 40  of  1702 ) because features have only one measurement across MS runs.
Can't summarize for   ( 44  of  1702 ) because features have only one measurement across MS runs.
Can't summarize for   ( 45  of  1702 ) because features have only one measurement across MS runs.
 == the summarization per subplot is done.
```

**Comment by mstaniak** [comment]
Well, if there's only a single measurement across all runs, there is no way to make group comparison based on the summary, so the summary is not useful anyway

**Comment by mstaniak** [comment]
Closing the issue, please  reach out if you have more questions
