### ISSUE TITLE
Only partial results from dataProcess

### ISSUE THREAD

**Issue by hanna6703** [Vitek-Lab/MSstats#80]
Hi,

I've been trying to analyse label-free DDA data using the MSstats.csv file from IonQuant. When using the dataProcess function, I've noticed that the resulting object is not a list of 5 but a list of 3. I contains FeatureLevelData, ProteinLevelData and SummaryMethod - with ProcessedData, RunlevelData, ModelQC and ProdictBySurvival missing (according to the manual "Protein significance analysis of mass spectrometry-based proteomics experiments with R and MSstats (v3.18.1) or later").

When using the inbuilt DDARawData the same happens, on my computer as well as on that of a friend. How can I obtain the processed data from dataProcess?

I'm using R 4.1.1, MSstats 4.2.0 and to get to the results I described I simply used dataProcess(DDARawData).

Thanks!
Hanna

**Comment by mstaniak** [comment]
It's all OK, we will update the manual soon. Current package documentation described the latest version, so it's better to use that. dataProcess returns a list of 3.
