### ISSUE TITLE
Values  below 1 being set to 1 in dataProcess function

### ISSUE THREAD

**Issue by ebrombacher** [Vitek-Lab/MSstats#82]
Hi,

We would like to perform protein summarization on data generated by Skyline using the dataProcess function. We noticed that when applying this function all intensities below 1 are set to 1. We were wondering what the reason for this is and if there exists a possibility to leave those intensities unchanged.

Thank you,

Eva

**Comment by mstaniak** [comment]
It's because log transformation for values smaller than 1 produces negative log-intensities.

**Comment by ebrombacher** [comment]
Many thanks for your prompt reply.
At least for our purposes we would prefer this behaviour (to keep those values over 0 and below 1 as they are, and set 0s to NA). It would be great if there would be some workaround which allows for this.

**Comment by mstaniak** [comment]
You can try to use the extended workflow - functions with names that start with MSstats (MSstatsNormalize etc) and replace the step that removes intensitites smaller than 1 with your intended treatment (there are examples in package documentation)

**Comment by ebrombacher** [comment]
Thank you for the helpful hint. We adjusted .preProcessIntensities, which is called in MSstatsPrepareForDataProcess, accordingly and it seems to do the trick.
