### ISSUE TITLE
Error with dataProcess 

### ISSUE THREAD

**Issue by xyztlmercury** [Vitek-Lab/MSstats#87]
Hi, 

I recently updated my R and MSstats since I cannot use the old version anymore. 

I used my script for earlier version of MSstats and got the error message below:
quant.skyline <- dataProcess(raw = input.skyline, 
+                              logTrans=2, 
+                              normalization = 'globalStandards', ##changed to global standard
+                              nameStandards = 'sp|Q9H6Q4|CIAO3_HUMAN',
+                              summaryMethod = 'TMP', 
+                              MBimpute=TRUE,
+                              censoredInt='0', ## important for Skyline
+                              cutoffCensored='minFeature',
+                              maxQuantileforCensored = 0.999)
**Error in dataProcess(raw = input.skyline, logTrans = 2, normalization = "globalStandards",  : 
  unused argument (cutoffCensored = "minFeature")**

I then removed the unused argument but still got an error:
quant.skyline <- dataProcess(raw = input.skyline, 
+                              logTrans=2, 
+                              normalization = 'globalStandards', ##changed to global standard
+                              nameStandards = 'sp|Q9H6Q4|CIAO3_HUMAN',
+                              summaryMethod = 'TMP', 
+                              MBimpute=TRUE,
+                              censoredInt='0', ## important for Skyline
+                              #cutoffCensored='minFeature',
+                              maxQuantileforCensored = 0.999)
**Error in if (cutoff_lower <= 0 & !is.null(missing_symbol) & missing_symbol ==  : 
  missing value where TRUE/FALSE needed**

I am wondering if you could help me with it. 

Thank you.

**Comment by mstaniak** [comment]
Can you share a small data example that reproduces this issue?

**Comment by xyztlmercury** [comment]
Dear Mateusz,

Thank you very much for your reply.

I have attached the MSstats input file, annotation file as well as the R
script that produces this issue.

Please don't hesitate to let me know if you need additional information
from my side.

Thank you and I am looking forward to your reply.

Sincerely,
Xiaorui

**Comment by xyztlmercury** [comment]
Hi Mateusz,

I replied this email directly last time. I am wondering if there is another
email address that I could use?

Thank you and I'm looking forward to your reply.

Sincerely,
Xiaorui

**Comment by mstaniak** [comment]
Hi,
please use the e-mail address indicated in the DESCRIPTION file of the package
