### ISSUE TITLE
Contribution guidelines and unit testing

### ISSUE THREAD

**Issue by jspaezp** [Vitek-Lab/MSstats#90]
Hello!

I was wondering whether the project is taking contributions and whether there are any guidelines for it?
In particular I believe there are a couple of places where performance optimization can be made but I fail to find a testing suite to make sure the changes don't brake an use case other than mine. Is there any repository where sample input files can be found for the supported input types?

Kindest wishes,
Sebastian

**Comment by jspaezp** [comment]
Discussed originally here ... in 2018 ...
https://github.com/Vitek-Lab/MSstats/pull/20#issuecomment-392636600

**Comment by mstaniak** [comment]
Short story: https://github.com/Vitek-Lab/MSstats/wiki/Contributing-guidelines
what optimizations do you have in mind?

**Comment by mstaniak** [comment]
Please start a pull request if you have any particular changes in mind, closing the issue for now
