### ISSUE TITLE
Differential analysis when there is only protein level data

### ISSUE THREAD

**Issue by Mengbo-Li** [Vitek-Lab/MSstats#91]
Hi all, 

Thanks for the great software and I just have a quick question. What is your recommended workflow when all you get is the protein-level data, eg, Maxlfq summarised protein intensities in a protein-by-sample matrix from DIA experiments. Is there an imputation method you recommend in this case? Or do I do `groupComparison()` after converting the protein-by-sample matrix into the `dataProcessed$ProteinLevelData` sort of long format where each observation is a row, with missing values removed?

Cheers, 
Mengbo

**Comment by mstaniak** [comment]
Hi, the recommended workflow is to start with feature-level data (evidence and proteinGroups files), is it impossible?

**Comment by Mengbo-Li** [comment]
Hi, thanks a lot for the reply. No there is no feature-level data, but only the protein group level MaxLFQ values. So the way to go at this is to make a pseudo output list like those dataProcess() produces, and make @ProteinLevelData the long format based on my MaxLFQ matrix?

Also, could I ask one more tag along question here?

When I run dataProcess(), does it make a difference if I just let condition/bioreplicate be the same as RUN? Does it depend on whether I let normlization and/or imputation be TRUE?

Cheers
Mengbo

**Comment by mstaniak** [comment]
Yes, that's the way to go.
RUN denotes a single replicate of the experiment. If combination of Condition and Biological Replicate is enough to denote that, it's OK. WIth technical replicates, fractionation etc combination of Condition and BioRep is not unique, so it's not OK.
There is no normalization or imputation at the protein-level, but at the feature-level run labels matter for both.

**Comment by Mengbo-Li** [comment]
Thank a lot! This is really helpful.

One final question, with DIA-NN report, NA observations are not output. I am just wondering if dataProcess() requires "every" observation in a row, including the NAs. Say we have 2 sample and 3 precursors, with one precursor missing in a sample. Would dataProcess() expect a 6-row or a 5-row input?

(In fact I have tried both ways on my data, the results are identical, but just want to make sure with the authors again. Thanks heaps! )

**Comment by mstaniak** [comment]
It's been a long time but DIA-NN has values for all the samples in a single column, we use all of them. Please reopen the issue if needed
