### ISSUE TITLE
Aggregate function missing: defaulting to length

### ISSUE THREAD

**Issue by kkw5710** [Vitek-Lab/MSstats#93]
Hi, I am trying to use dataProcess() in MSstats using raw data as my input instead of output data from a spectral processing tool (like Skyline or MaxQuant). I have cleaned the raw data so that it has the necessary variables and column names that MSstats requires, and there are no missing observations. The columns are as follows: Run, PeptideSequence, PeptideModifiedSequence, ProteinName, Intensity, PrecursorCharge, FragmentIon, ProductCharge, IsotopeLabelType, TechReplicate, Condition and BioReplicate. The only columns that have every observation as "NA" are FragmentIon and ProductCharge.

When I run dataProcess(), regardless of the parameters, I receive the following error:
![Screenshot (1)](https://user-images.githubusercontent.com/74326179/216833820-4507cd73-1f50-46af-88c7-11304c951a75.png)

Another individual had the same error and used the following code to fix it:
devtools::install_github("Vitek-Lab/MSstatsConvert", ref = "hotfix-techreplicate")
devtools::install_github("Vitek-Lab/MSstats", ref = "hotfix-fractions-check")

I have already tried it, and still received the same error. Any help with this problem would be greatly appreciated.

**Comment by kkw5710** [comment]
The data set I have is a provided example data set for me to practice using the MSstats package. I have noticed, however, that the values for the "Run" column are raw filenames and there are numerous rows with the same raw filenames, i.e., multiple rows in the data set have the same raw filename for the "Run" column. Would this be the problem you mention for your first question?

As far as I am aware, this data set is not from a fractionated experiment.

Lastly, I am unsure if this is the exact issue, but an example of the error is:

Given the following data set:
df <- data.frame(store=c('A', 'A', 'A', 'A', 'B', 'B', 'B', 'B'),
                 promotion=c('Y', 'Y', 'N', 'N', 'Y', 'Y', 'N', 'N'),
                 product=c(1, 2, 1, 2, 1, 2, 1, 2),
                 sales=c(12, 18, 29, 20, 30, 11, 15, 22))

When trying to convert the data frame to a wide format with the following code,

df_wide <- dcast(df, store ~ product, value.var="sales")

the same error will arise. 

Aggregation function missing: defaulting to length

The only explanation I can think of is that during the dataProcess() function in MSstats, 
the data set must be converted to a wide format, but because of the repeated "Run" values for multiple rows, the function cannot properly convert the format. If this is indeed the issue, how would you suggest I fix it?

Thank you for your assistance.

**Comment by mstaniak** [comment]
Hi,
please count observations by (Protein, Feature,  Run, Label). There should be a single value for each combination of unique values of these columns. dataProcess operates under this assumptions (you are correct that we switch to wide format at one point). Because of this MSstats converters (see implementation in MSstatsConvert::MSstatsPreprocess) take maximum or sum of peaks for each feature in each run.

**Comment by kkw5710** [comment]
Unfortunately, I am still having difficulty understanding what you mean. Here is a snippet of my raw data set. 

![Screenshot (5)](https://user-images.githubusercontent.com/74326179/219528660-4b9b1ce5-c7db-4a5c-8a07-9accf3e40234.png)

I have replaced the repetitive file names for the Run column with unique numeric values (1, 2, 3, ...., n), which I thought would resolve the issue when I used dataProcess(). And although I am no longer receiving the aggregate function error, I am receiving a new one. 

![Screenshot (7)](https://user-images.githubusercontent.com/74326179/219529285-a12bcea8-3d08-487b-a0ba-5f545915e492.png)

There are no missing or repetitive observations in the Run column, so I do not know what could be causing the error.

Also, when you say to count observations by Protein, Feature, Run and Label, which columns are you referring to out of the columns I have in my data set? I do understand that for each combination of unique values of these four columns, there should only be a single value, but I thought that after creating unique values for each observation in my Run column, the issue would be resolved. 

I apologize for any confusion, and thank you for your patience.

**Comment by kkw5710** [comment]
Hi! I have found numerous unique combinations of the columns ProteinName, PeptideSequence, Run and IsotopeLabelType where there exists more than a single value. What would you suggest I do so that I am no longer receiving the aggregate function error?

Thank you for your continued patience.

**Comment by mstaniak** [comment]
Hi, please see the documentation for MSstatsPreprocess function from MSstatsConvert. This function was designed to help re-shape arbitrary data into a format suitable for analysis with dataProcess function. If you have any question regarding its use, please let me know.

**Comment by kkw5710** [comment]
I understand that the MSstatsPreprocess function will re-shape the data into the correct format for dataProcess. However, the documentation I have read about the MSstatsPreprocess function all applies to output from a spectral processing tool (Skyline, MaxQuant, etc.). The data I am using is raw data NOT from any processing tool, and I have not found any documentation about MSstatsPreprocess that applies to data not from a processing tool. Furthermore, it is my understanding that before I can even run MSstatsPreprocess, I must run my data through MSstatsClean (which is the input for MSstatsPreprocess). Again, there exists no documentation about raw data not from any processing tool being used as input for MSstatsClean. So, how would I go about running MSstatsClean or MSstatsPreprocess when it appears as though I cannot if my data is not from a processing tool?

**Comment by kkw5710** [comment]
The following are all of the file types that the MSstatsClean accepts that I have found in the documentation.
Clean DIAUmpire files
Clean MaxQuant files
Clean OpenMS files
Clean OpenSWATH files
Clean Progenesis files
Clean ProteomeDiscoverer files Clean Skyline files
Clean SpectroMine files
Clean Spectronaut files
Clean Philosopher files
Clean DIA-NN files
My data is not from any processing tool and thus, would not be applicable to the MSstatsClean function nor the MSstatsPreprocess function, consequently. How would I be able to use either?

**Comment by mstaniak** [comment]
MSstatsClean only transforms data from "raw" format to a data.frame with columns which you listed in the original question. MSstatsPreprocess can be used on any table with these columns (your data is already in the right format for MSstatsPreprocess)

**Comment by kkw5710** [comment]
Thank you for your help and patience. I am no longer receiving the error.
