### ISSUE TITLE
Importing DIANN in MSstats shiny

### ISSUE THREAD

**Issue by NinaRadzey** [Vitek-Lab/MSstats#94]
Hi there,

I am currently playing around with some preliminary DIA data that has been processed using DIANN. 
As I am still quite unfamiliar with the MSstats package I was hoping to use MSstats shiny to get a better idea of the code, however I do not see an option to import output generated by DIANN? Is this possible at the moment?

Alternatively, is there any documentation on using DIANN data in MSstats in R directly?

Thank you!

**Comment by devonjkohler** [comment]
Hi @NinaRadzey,

The newest version of MSstatsShiny now includes the DIANN converter. It should be up on Bioconductor tomorrow, but in the meantime you can install it directly from Github.

Best,
Devon
