### ISSUE TITLE
problem with dataProcess()

### ISSUE THREAD

**Issue by Yck711** [Vitek-Lab/MSstats#99]
Hello,
   I encountered an issue while running dataProcess. The error code is as follows：

               Error in setnames(x, value): Unable to assign names to 4 columns of 0-length data.table.

After investigation, it was found that the error occurred in the function .checkDataValidity() due to unknown reasons, causing the input to become an empty data.frame.

Thank you!

###################################################
normalized_data_SP <- dataProcess(msstat_input_SP,
                               logTrans = 2,
                               normalization = "equalizeMedians",
                               nameStandards = NULL,
                               featureSubset = "all",
                               remove_uninformative_feature_outlier = FALSE,
                               n_top_feature = 3,
                               summaryMethod = "TMP",
                               equalFeatureVar = TRUE,
                               censoredInt = "NA",
                               MBimpute = TRUE,
                               remove50missing = FALSE,
                               maxQuantileforCensored = 0.999)
####################################################
[MSstats_dataProcess_log_2023_06_07_11_02_40.162773.log](https://github.com/Vitek-Lab/MSstats/files/11674340/MSstats_dataProcess_log_2023_06_07_11_02_40.162773.log)

**Comment by mstaniak** [comment]
Hi,
which converter did you use before running dataProcess?

**Comment by mstaniak** [comment]
Closing as inactive, please re-open if needed
